/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Studentdb_Mysql;

/**
 *
 * @author NAWAB
 */
public class Studentdb_Mysql extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Studentdb_Mysql.class.getName());

    /**
     * Creates new form Studentdb_Mysql
     */
    public Studentdb_Mysql() {
        initComponents();
        
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jtxtCoursecode = new javax.swing.JTextField();
        jtxtFacultyName = new javax.swing.JTextField();
        jtxtCourseTutor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtDeanofFaculty = new javax.swing.JTextField();
        jtxtProgrameLeader = new javax.swing.JTextField();
        jtxtCourse = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jcboGender = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jcboGender19 = new javax.swing.JComboBox<>();
        jtxtFirstname1 = new javax.swing.JTextField();
        jcboGender20 = new javax.swing.JComboBox<>();
        jtxtFirstname2 = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jcboGender21 = new javax.swing.JComboBox<>();
        jtxtFirstname3 = new javax.swing.JTextField();
        jcboGender22 = new javax.swing.JComboBox<>();
        jtxtFirstname4 = new javax.swing.JTextField();
        jcboGender24 = new javax.swing.JComboBox<>();
        jcboGender25 = new javax.swing.JComboBox<>();
        jcboGender26 = new javax.swing.JComboBox<>();
        jcboGender27 = new javax.swing.JComboBox<>();
        jcboGender28 = new javax.swing.JComboBox<>();
        jcboGender29 = new javax.swing.JComboBox<>();
        jtxtFirstname5 = new javax.swing.JTextField();
        jtxtFirstname7 = new javax.swing.JTextField();
        jtxtFirstname8 = new javax.swing.JTextField();
        jtxtFirstname9 = new javax.swing.JTextField();
        jtxtFirstname10 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jtxtFirstname11 = new javax.swing.JTextField();
        jtxtFirstname12 = new javax.swing.JTextField();
        jtxtFirstname13 = new javax.swing.JTextField();
        jtxtFirstname14 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jcboGender2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jcboGender3 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jcboGender4 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jtxtmobile = new javax.swing.JTextField();
        jtxtAdress = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jtxtfirstname = new javax.swing.JTextField();
        jcboGuidance = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jcboGender14 = new javax.swing.JComboBox<>();
        jcboGender15 = new javax.swing.JComboBox<>();
        jcboGender16 = new javax.swing.JComboBox<>();
        jcboGender17 = new javax.swing.JComboBox<>();
        jcboGender18 = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jcboGender1 = new javax.swing.JComboBox<>();
        jcboGender10 = new javax.swing.JComboBox<>();
        jcboGender11 = new javax.swing.JComboBox<>();
        jcboGender12 = new javax.swing.JComboBox<>();
        jcboGender13 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));
        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        getContentPane().add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Course");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel4.add(jtxtCoursecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 20));
        jPanel4.add(jtxtFacultyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 20));
        jPanel4.add(jtxtCourseTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 170, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Course Tutor");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Program Leader");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Dean of Faculty");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Faculty Name");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Course Code");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel4.add(jtxtDeanofFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 20));
        jPanel4.add(jtxtProgrameLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, 20));

        jtxtCourse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "BSc in Information Technology", "BSc in Software Engineering", "BSc in Data Science", "BSc in Artificial Intelligence", "BSc in Cyber Security", "BSc in Computer Engineering", "BSc in Statistics", "BSc in Data Analytics" }));
        jPanel4.add(jtxtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 170, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 450, 300));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setText("Exit");
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton2.setText("Add");
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton3.setText("Reset");
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton4.setText("Result");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 450, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student ID");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Firstname");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Surname");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Address");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("DOB");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mobile");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Email");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jtxtEmail.addActionListener(this::jtxtEmailActionPerformed);
        jPanel6.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 170, 20));
        jPanel6.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 170, 30));
        jPanel6.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 30));
        jPanel6.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 30));
        jPanel6.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, -1));
        jPanel6.add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 20));
        jPanel6.add(jtxtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 20));

        jcboGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel6.add(jcboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 330));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel54.setText("Score");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 80, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setText("No");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 40, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setText("Module Selector");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("3");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 40, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("1");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 40, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("2");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("4");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("5");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("6");
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 40, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("8");
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 40, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("7");
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 40, -1));

        jcboGender19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 160, -1));
        jPanel7.add(jtxtFirstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, 30));

        jcboGender20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 30));
        jPanel7.add(jtxtFirstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 70, 30));

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setText("Score");
        jPanel30.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("No");
        jPanel30.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setText("Module Selector");
        jPanel30.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("3");
        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 40, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("1");
        jLabel69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("2");
        jLabel70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 40, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("4");
        jLabel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, -1));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("5");
        jLabel72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 40, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("6");
        jLabel73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 40, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("8");
        jLabel74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 40, -1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("7");
        jLabel75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 40, -1));

        jcboGender21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel30.add(jcboGender21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, -1));
        jPanel30.add(jtxtFirstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, 30));

        jcboGender22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel30.add(jcboGender22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, -1));
        jPanel30.add(jtxtFirstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, 30));

        jPanel7.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 380, 570));

        jcboGender24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, -1));

        jcboGender25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, -1));

        jcboGender26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 160, -1));

        jcboGender27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 160, -1));

        jcboGender28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 160, -1));

        jcboGender29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel7.add(jcboGender29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 160, 20));
        jPanel7.add(jtxtFirstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 70, 20));
        jPanel7.add(jtxtFirstname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 70, -1));
        jPanel7.add(jtxtFirstname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 70, 30));
        jPanel7.add(jtxtFirstname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 70, -1));
        jPanel7.add(jtxtFirstname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 70, 20));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel76.setText("Date");
        jPanel7.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel77.setText("Total Score ");
        jPanel7.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, -1));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel78.setText("Ranking");
        jPanel7.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));
        jPanel7.add(jtxtFirstname11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 70, 30));
        jPanel7.add(jtxtFirstname12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 190, 20));
        jPanel7.add(jtxtFirstname13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 190, 20));
        jPanel7.add(jtxtFirstname14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 190, 20));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 380, 570));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcboGender2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel27.add(jcboGender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Student ID");
        jPanel27.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField11.setText("jTextField1");
        jPanel27.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 20));

        jTextField12.setText("jTextField1");
        jPanel27.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 20));

        jTextField6.setText("jTextField1");
        jPanel27.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Student ID");
        jPanel27.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Student ID");
        jPanel27.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Student ID");
        jPanel27.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Student ID");
        jPanel27.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Student ID");
        jPanel27.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField13.setText("jTextField1");
        jPanel27.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));

        jTextField14.setText("jTextField1");
        jPanel27.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 20));

        jPanel8.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 390, 300));

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcboGender3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel28.add(jcboGender3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Student ID");
        jPanel28.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField15.setText("jTextField1");
        jPanel28.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 20));

        jTextField16.setText("jTextField1");
        jPanel28.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 20));

        jTextField17.setText("jTextField1");
        jPanel28.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Student ID");
        jPanel28.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Student ID");
        jPanel28.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Student ID");
        jPanel28.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Student ID");
        jPanel28.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Student ID");
        jPanel28.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField18.setText("jTextField1");
        jPanel28.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));

        jTextField19.setText("jTextField1");
        jPanel28.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 20));

        jPanel8.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 390, 300));

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcboGender4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGender4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel29.add(jcboGender4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Student ID");
        jPanel29.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField20.setText("jTextField1");
        jPanel29.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 20));

        jTextField21.setText("jTextField1");
        jPanel29.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 20));

        jTextField22.setText("jTextField1");
        jPanel29.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Student ID");
        jPanel29.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Student ID");
        jPanel29.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Student ID");
        jPanel29.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Student ID");
        jPanel29.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Student ID");
        jPanel29.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField23.setText("jTextField1");
        jPanel29.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));

        jTextField24.setText("jTextField1");
        jPanel29.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 20));

        jPanel8.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 390, 300));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Email");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Mobile");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Adress");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("Surname");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("Firstname");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setText("Guidance");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField25.addActionListener(this::jTextField25ActionPerformed);
        jPanel8.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 20));
        jPanel8.add(jtxtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 20));

        jtxtAdress.addActionListener(this::jtxtAdressActionPerformed);
        jPanel8.add(jtxtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));
        jPanel8.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 20));
        jPanel8.add(jtxtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 20));

        jcboGuidance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboGuidance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male" }));
        jPanel8.add(jcboGuidance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 410, 230));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setText("PHD");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setText("MSc");
        jPanel12.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setText("BSc");
        jPanel12.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setText("MA");
        jPanel12.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel53.setText("BA");
        jPanel12.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jcboGender14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel12.add(jcboGender14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, -1));

        jcboGender15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel12.add(jcboGender15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, -1));

        jcboGender16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel12.add(jcboGender16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));

        jcboGender17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel12.add(jcboGender17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, -1));

        jcboGender18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel12.add(jcboGender18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 200, 180));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel21.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel17.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setText("Scholarship");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setText("Exchange");
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setText("Accommodation");
        jPanel17.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setText("Overseas");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setText("Home Student");
        jPanel17.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jcboGender1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jcboGender1.setToolTipText("");
        jPanel17.add(jcboGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, -1));

        jcboGender10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jPanel17.add(jcboGender10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 30));

        jcboGender11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jcboGender11.setToolTipText("");
        jPanel17.add(jcboGender11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 70, -1));

        jcboGender12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jcboGender12.setToolTipText("");
        jPanel17.add(jcboGender12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 70, -1));

        jcboGender13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboGender13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jcboGender13.setToolTipText("");
        jPanel17.add(jcboGender13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, -1));

        jPanel3.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 240, 180));

        jTabbedPane7.addTab("School System", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 6, 90, -1));

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 59, -1, -1));

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Firstname", "Surname", "Address", "Gender", "DOB", "Mobile", "Email", "Course", "CourseCode", "HomeStudent", "OverseaStudent", "Accommodation", "Exchange", "Scholarship", "BA", "BSc", "MA", "MSc", "PHD", "Module 1", "Module 2", "Module 3", "Module 4", "Module 5", "Module 6", "Module 7", "Module 8", "Score 1", "Score 2", "Score 3", "Score 4", "Score 5", "Score 6", "Score 7", "Score 8", "TotalScore", "Ranking", "Dates"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel35.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1140, -1));

        jPanel25.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1210, 470));

        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel43.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel45.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel43.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel49.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel47.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jPanel43.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Student Details Management System");
        jPanel43.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 50));

        jPanel25.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1210, 60));

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1250, 680));

        jTabbedPane7.addTab("Student Details", jPanel1);

        getContentPane().add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1300, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdressActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Studentdb_Mysql().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JComboBox<String> jcboGender1;
    private javax.swing.JComboBox<String> jcboGender10;
    private javax.swing.JComboBox<String> jcboGender11;
    private javax.swing.JComboBox<String> jcboGender12;
    private javax.swing.JComboBox<String> jcboGender13;
    private javax.swing.JComboBox<String> jcboGender14;
    private javax.swing.JComboBox<String> jcboGender15;
    private javax.swing.JComboBox<String> jcboGender16;
    private javax.swing.JComboBox<String> jcboGender17;
    private javax.swing.JComboBox<String> jcboGender18;
    private javax.swing.JComboBox<String> jcboGender19;
    private javax.swing.JComboBox<String> jcboGender2;
    private javax.swing.JComboBox<String> jcboGender20;
    private javax.swing.JComboBox<String> jcboGender21;
    private javax.swing.JComboBox<String> jcboGender22;
    private javax.swing.JComboBox<String> jcboGender24;
    private javax.swing.JComboBox<String> jcboGender25;
    private javax.swing.JComboBox<String> jcboGender26;
    private javax.swing.JComboBox<String> jcboGender27;
    private javax.swing.JComboBox<String> jcboGender28;
    private javax.swing.JComboBox<String> jcboGender29;
    private javax.swing.JComboBox<String> jcboGender3;
    private javax.swing.JComboBox<String> jcboGender4;
    private javax.swing.JComboBox<String> jcboGuidance;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JComboBox<String> jtxtCourse;
    private javax.swing.JTextField jtxtCourseTutor;
    private javax.swing.JTextField jtxtCoursecode;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDeanofFaculty;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFacultyName;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtFirstname1;
    private javax.swing.JTextField jtxtFirstname10;
    private javax.swing.JTextField jtxtFirstname11;
    private javax.swing.JTextField jtxtFirstname12;
    private javax.swing.JTextField jtxtFirstname13;
    private javax.swing.JTextField jtxtFirstname14;
    private javax.swing.JTextField jtxtFirstname2;
    private javax.swing.JTextField jtxtFirstname3;
    private javax.swing.JTextField jtxtFirstname4;
    private javax.swing.JTextField jtxtFirstname5;
    private javax.swing.JTextField jtxtFirstname7;
    private javax.swing.JTextField jtxtFirstname8;
    private javax.swing.JTextField jtxtFirstname9;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtProgrameLeader;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtfirstname;
    private javax.swing.JTextField jtxtmobile;
    // End of variables declaration//GEN-END:variables
}
